name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Cache Node.js modules
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Install client dependencies
      - name: Install Client Dependencies
        run: npm install --prefix client

      # Run linting
      - name: Run Lint
        run: npx eslint .

      # Build the React app
      - name: Build React App
        run: npm run build

      # Run tests (pass if no tests)
      - name: Run Tests
        run: cd client && npm test -- --watchAll=false --passWithNoTests

      # Upload Pages artifact
      - name: Upload Pages artifact
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./client/build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4
